# TUC SoftNet Cluster profile
# YARN mode with HDFS on clu01.softnet.tuc.gr
include "application.conf"

app {
  spark {
    master = "yarn"
  }

  paths {
    data-dir = "/user/chrisa/ml-latest"
    output-dir = "/user/fp25_1/ProjectOutputs"
  }

  hadoop {
    fs {
      defaultFS = "hdfs://clu01.softnet.tuc.gr:8020"
    }
    yarn {
      resourcemanager.address = "http://clu01.softnet.tuc.gr:8189"
      application.classpath = "$HADOOP_CONF_DIR,$HADOOP_COMMON_HOME/*,$HADOOP_COMMON_HOME/lib/*,$HADOOP_HDFS_HOME/*,$HADOOP_HDFS_HOME/lib/*,$HADOOP_MAPRED_HOME/*,$HADOOP_MAPRED_HOME/lib/*,$HADOOP_YARN_HOME/*,$HADOOP_YARN_HOME/lib/*"
    }
  }
}
